[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$ProductIdentityPath,
    [Parameter(Mandatory)]
    [ValidatePattern('^\d+\.\d+\.\d+$')]
    [string]$ProductVersion,
    [Parameter(Mandatory)]
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Convert-GuidToRfc4122Bytes([guid]$Guid) {
    $bytes = $Guid.ToByteArray()
    [byte[]]@(
        $bytes[3], $bytes[2], $bytes[1], $bytes[0],
        $bytes[5], $bytes[4], $bytes[7], $bytes[6],
        $bytes[8], $bytes[9], $bytes[10], $bytes[11],
        $bytes[12], $bytes[13], $bytes[14], $bytes[15])
}

function Convert-Rfc4122BytesToGuid([byte[]]$Bytes) {
    $native = [byte[]]@(
        $Bytes[3], $Bytes[2], $Bytes[1], $Bytes[0],
        $Bytes[5], $Bytes[4], $Bytes[7], $Bytes[6],
        $Bytes[8], $Bytes[9], $Bytes[10], $Bytes[11],
        $Bytes[12], $Bytes[13], $Bytes[14], $Bytes[15])
    [guid]::new($native)
}

function Get-UuidV5([guid]$Namespace, [string]$Name) {
    $namespaceBytes = Convert-GuidToRfc4122Bytes $Namespace
    $nameBytes = [System.Text.Encoding]::UTF8.GetBytes($Name)
    $inputBytes = New-Object byte[] ($namespaceBytes.Length + $nameBytes.Length)
    [Array]::Copy($namespaceBytes, 0, $inputBytes, 0, $namespaceBytes.Length)
    [Array]::Copy($nameBytes, 0, $inputBytes, $namespaceBytes.Length, $nameBytes.Length)
    $sha1 = [System.Security.Cryptography.SHA1]::Create()
    try { $hash = $sha1.ComputeHash($inputBytes) }
    finally { $sha1.Dispose() }
    $uuid = [byte[]]$hash[0..15]
    $uuid[6] = [byte](($uuid[6] -band 0x0f) -bor 0x50)
    $uuid[8] = [byte](($uuid[8] -band 0x3f) -bor 0x80)
    Convert-Rfc4122BytesToGuid $uuid
}

function Read-Define([string]$Text, [string]$Name) {
    $match = [regex]::Match($Text, '<\?define\s+' + [regex]::Escape($Name) + '\s*=\s*"([^"]+)"\s*\?>')
    if (-not $match.Success) { throw "Missing WiX identity define: $Name" }
    $match.Groups[1].Value
}

$identityText = Get-Content -Raw -Encoding UTF8 -LiteralPath $ProductIdentityPath
$lineKey = Read-Define $identityText 'StockIpoReminderProductLineKey'
$namespace = [guid](Read-Define $identityText 'StockIpoReminderProductCodeNamespace')
$productCode = Get-UuidV5 $namespace "$lineKey|$ProductVersion"
$content = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-wix-product-instance.ps1. -->
<Include xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <?define StockIpoReminderProductVersion = "$ProductVersion" ?>
  <?define StockIpoReminderProductCode = "{$($productCode.ToString().ToUpperInvariant())}" ?>
</Include>
"@

$parent = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Path $parent -Force | Out-Null
[System.IO.File]::WriteAllText($OutputPath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated MSI identity for version $ProductVersion"
